# Generated by Django 4.0.4 on 2022-05-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('videoURL', models.URLField(blank=True, verbose_name='URL Видео')),
                ('sort', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('qntView', models.IntegerField(default=0, verbose_name='Кол-во показов')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
            },
        ),
    ]
