# Generated by Django 4.0.4 on 2022-05-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='qntView',
            field=models.IntegerField(blank=True, default=0, verbose_name='Кол-во показов'),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='sort',
            field=models.IntegerField(blank=True, default=500, verbose_name='Сортировка'),
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slag', models.CharField(blank=True, max_length=100, verbose_name='Слаг')),
                ('sort', models.IntegerField(blank=True, default=500, verbose_name='Сортировка')),
                ('blocks', models.ManyToManyField(to='pages.blocks')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
