# Generated by Django 4.0.4 on 2022-05-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_blocks_qntview_alter_blocks_sort_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='blocks',
            field=models.ManyToManyField(blank=True, to='pages.blocks', verbose_name='Блоки'),
        ),
    ]
